import Head from 'next/head';
import Left4 from '@/components/Left4';
import Right from '@/components/Right';
import { useState } from 'react';

export default function Home() {
  const [optionNum, setOptionNum] = useState(0)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container d-md-flex mt-5'>
        <Left4 setOptionNum={setOptionNum} />
        <Right optionNum={optionNum} />
      </main>
    </>
  )
}
